import Link from 'next/link';
import { ArrowRight, BedDouble, ClipboardList, LayoutDashboard, Settings, UtensilsCrossed, Waves } from 'lucide-react';

export default function ManagerDashboard() {
  return (
    <div className="min-h-screen bg-[#F8F5EE] text-[#182326]">
      <header className="border-b border-[#0B3D4A]/10 bg-[#0B3D4A] text-white"><div className="mx-auto flex max-w-7xl items-center gap-3 px-4 py-4 md:px-6"><img src="/tule-resort-mark.svg" alt="Tule Resort" className="h-11 w-14 rounded-lg object-cover" /><div><p className="font-display text-2xl">Tule Resort</p><p className="text-[9px] font-bold uppercase tracking-[.25em] text-white/45">Manager Dashboard</p></div></div></header>
      <main className="mx-auto max-w-7xl px-4 py-7 md:px-6 md:py-10">
        <section className="mb-8"><p className="text-[10px] font-black uppercase tracking-[.25em] text-[#159A9C]">Control center</p><h1 className="mt-2 font-display text-5xl md:text-7xl">Manage Tule Resort.</h1><p className="mt-3 max-w-2xl text-sm leading-relaxed text-[#182326]/55">Manage your menu, resort services, rooms and guest requests from one place. Content changes are stored in Supabase and appear on the customer website.</p></section>
        <section className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
          <Link href="/staff/dashboard/menu" className="group rounded-[2rem] border border-[#159A9C]/20 bg-white p-6 shadow-sm transition hover:-translate-y-1"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[#159A9C] text-white"><UtensilsCrossed className="h-6 w-6" /></div><p className="mt-5 text-[9px] font-black uppercase tracking-[.23em] text-[#159A9C]">CMS</p><h2 className="mt-1 font-display text-3xl">Food Menu</h2><p className="mt-2 text-sm leading-relaxed text-[#182326]/50">Add, edit, delete and publish food items with images, prices and descriptions.</p><div className="mt-5 flex items-center gap-2 text-xs font-black uppercase tracking-wider text-[#0B3D4A]">Manage menu <ArrowRight className="h-4 w-4 transition group-hover:translate-x-1" /></div></Link>
          <Link href="/staff/dashboard/services" className="group rounded-[2rem] border border-[#0B3D4A]/10 bg-white p-6 shadow-sm transition hover:-translate-y-1"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[#0B3D4A] text-white"><Waves className="h-6 w-6" /></div><p className="mt-5 text-[9px] font-black uppercase tracking-[.23em] text-[#159A9C]">CMS</p><h2 className="mt-1 font-display text-3xl">Resort Services</h2><p className="mt-2 text-sm leading-relaxed text-[#182326]/50">Manage pool, dining, wellness, leisure and every guest-facing resort service.</p><div className="mt-5 flex items-center gap-2 text-xs font-black uppercase tracking-wider text-[#0B3D4A]">Manage services <ArrowRight className="h-4 w-4 transition group-hover:translate-x-1" /></div></Link>
          <Link href="/staff/dashboard/rooms" className="group rounded-[2rem] border border-[#0B3D4A]/10 bg-white p-6 shadow-sm transition hover:-translate-y-1"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[#159A9C] text-white"><BedDouble className="h-6 w-6" /></div><p className="mt-5 text-[9px] font-black uppercase tracking-[.23em] text-[#159A9C]">CMS</p><h2 className="mt-1 font-display text-3xl">Rooms</h2><p className="mt-2 text-sm leading-relaxed text-[#182326]/50">Manage room details, photos, prices, amenities and booking availability.</p><div className="mt-5 flex items-center gap-2 text-xs font-black uppercase tracking-wider text-[#0B3D4A]">Manage rooms <ArrowRight className="h-4 w-4 transition group-hover:translate-x-1" /></div></Link>
          <Link href="/admin/orders" className="group rounded-[2rem] border border-[#0B3D4A]/10 bg-white p-6 shadow-sm transition hover:-translate-y-1"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[#0B3D4A]/10"><ClipboardList className="h-6 w-6 text-[#159A9C]" /></div><p className="mt-5 text-[9px] font-black uppercase tracking-[.23em] text-[#182326]/35">Operations</p><h2 className="mt-1 font-display text-3xl">Orders & Requests</h2><p className="mt-2 text-sm leading-relaxed text-[#182326]/50">Review guest food orders and service requests.</p><div className="mt-5 flex items-center gap-2 text-xs font-black uppercase tracking-wider text-[#0B3D4A]">Open operations <ArrowRight className="h-4 w-4 transition group-hover:translate-x-1" /></div></Link>
        </section>
        <section className="mt-6 rounded-[2rem] border border-[#0B3D4A]/10 bg-[#0B3D4A] p-5 text-white"><div className="flex items-center gap-3"><LayoutDashboard className="h-5 w-5 text-[#159A9C]" /><div><p className="text-sm font-bold">Next CMS modules</p><p className="text-xs text-white/45">Events • Gallery • Homepage content • Booking management</p></div></div></section>
      </main>
    </div>
  );
}
