'use client';

import { FormEvent, useEffect, useState } from 'react';
import { FileText, Plus, Printer } from 'lucide-react';
import supabase from '@/lib/supabaseClient';

type Receipt={id:string;receipt_number:string;guest_name:string;room_number:string|null;subtotal:number;service_charge:number;tax:number;total:number;currency:string;payment_method:string;processed_by:string|null;created_at:string}
export default function ReceiptsPage(){const [items,setItems]=useState<Receipt[]>([]);const [guest,setGuest]=useState('');const [room,setRoom]=useState('');const [subtotal,setSubtotal]=useState('');const [payment,setPayment]=useState('pay_at_resort');const [saving,setSaving]=useState(false);const [message,setMessage]=useState('');
 async function load(){const {data}=await supabase.from('resort_receipts').select('*').order('created_at',{ascending:false}).limit(50);setItems(data??[])}useEffect(()=>{void load()},[])
 async function create(e:FormEvent){e.preventDefault();setSaving(true);setMessage('');const base=Number(subtotal||0);const {data:settings}=await supabase.from('resort_settings').select('service_charge_percent,tax_percent,default_currency').eq('id',true).single();const servicePct=Number(settings?.service_charge_percent||0),taxPct=Number(settings?.tax_percent||0),service=base*servicePct/100,tax=(base+service)*taxPct/100,total=base+service+tax;const {error}=await supabase.from('resort_receipts').insert({guest_name:guest.trim(),room_number:room.trim()||null,subtotal:base,service_charge_percent:servicePct,service_charge:service,tax_percent:taxPct,tax,total,currency:settings?.default_currency||'ETB',payment_method:payment});setSaving(false);if(error)setMessage(error.message);else{setMessage('Receipt created.');setGuest('');setRoom('');setSubtotal('');await load()}}
 return <main className="min-h-screen bg-[#F8F5EE] px-5 py-10 text-[#182326] md:px-8"><div className="mx-auto max-w-6xl"><div className="flex items-center gap-4"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[#0B3D4A] text-white"><FileText/></div><div><p className="text-[10px] font-black uppercase tracking-[.22em] text-[#159A9C]">Billing</p><h1 className="font-display text-4xl">Receipts</h1></div></div><form onSubmit={create} className="mt-8 grid gap-4 rounded-[2rem] bg-white p-6 md:grid-cols-4"><input required value={guest} onChange={e=>setGuest(e.target.value)} placeholder="Guest name" className="field-input"/><input value={room} onChange={e=>setRoom(e.target.value)} placeholder="Room number" className="field-input"/><input required type="number" min="0" step="0.01" value={subtotal} onChange={e=>setSubtotal(e.target.value)} placeholder="Subtotal (ETB)" className="field-input"/><select value={payment} onChange={e=>setPayment(e.target.value)} className="field-input"><option value="pay_at_resort">Pay at resort</option><option value="telebirr">Telebirr</option><option value="cbe_birr">CBE Birr</option><option value="bank_transfer">Bank transfer</option></select><button disabled={saving} className="inline-flex items-center justify-center gap-2 rounded-full bg-[#0B3D4A] px-5 py-3 text-xs font-black uppercase tracking-wider text-white md:col-span-4"><Plus className="h-4 w-4"/>{saving?'Creating…':'Create receipt'}</button>{message&&<p className="text-sm font-semibold md:col-span-4">{message}</p>}</form><div className="mt-7 overflow-x-auto rounded-[2rem] bg-white"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-[#0B3D4A] text-white"><tr><th className="p-4">Receipt</th><th className="p-4">Guest</th><th className="p-4">Subtotal</th><th className="p-4">Charges</th><th className="p-4">Total</th><th className="p-4">Payment</th><th className="p-4">Print</th></tr></thead><tbody>{items.map(r=><tr key={r.id} className="border-b border-black/5"><td className="p-4 font-bold">{r.receipt_number}</td><td className="p-4">{r.guest_name}{r.room_number&&<span className="block text-xs text-black/40">Room {r.room_number}</span>}</td><td className="p-4">{Number(r.subtotal).toLocaleString()} {r.currency}</td><td className="p-4">{(Number(r.service_charge)+Number(r.tax)).toLocaleString()} {r.currency}</td><td className="p-4 font-black">{Number(r.total).toLocaleString()} {r.currency}</td><td className="p-4 capitalize">{r.payment_method.replaceAll('_',' ')}</td><td className="p-4"><button onClick={()=>window.print()} className="rounded-lg bg-[#F8F5EE] p-2"><Printer className="h-4 w-4"/></button></td></tr>)}</tbody></table></div></div></main>}
